export const MOCK_AGENTS = [
  {
    id: 'agent-1',
    user_id: 'user-a1',
    phone: '+224620001001',
    name: 'Mamadou Diallo',
    badge: 'SGP-2021-0047',
    experience: 8,
    armed: true,
    bio: 'Ancien commandant des forces spéciales. Expert en protection rapprochée et gestion de crise.',
    competences: ['Protection VIP', 'Gestion de crise', 'Karaté 3e dan', 'Premiers secours', 'Conduite défensive'],
    rating: 4.9,
    missions_count: 143,
    available: true,
    commune: 'Kaloum',
    photo_url: null,
    mission_types: ['garde_corps_vip', 'escorte_securisee', 'protection_evenement'],
    status: 'active',
  },
  {
    id: 'agent-2',
    user_id: 'user-a2',
    phone: '+224620002002',
    name: 'Fatoumata Camara',
    badge: 'SGP-2022-0089',
    experience: 5,
    armed: false,
    bio: 'Spécialiste sécurité événementielle et protection diplomatique. Certifiée CACES.',
    competences: ['Sécurité événements', 'Protection diplomatique', 'Gestion foule', 'Secourisme PSC1'],
    rating: 4.8,
    missions_count: 87,
    available: true,
    commune: 'Dixinn',
    photo_url: null,
    mission_types: ['protection_evenement', 'securite_residentielle', 'garde_corps_vip'],
    status: 'active',
  },
  {
    id: 'agent-3',
    user_id: 'user-a3',
    phone: '+224620003003',
    name: 'Ibrahima Kouyaté',
    badge: 'SGP-2020-0023',
    experience: 10,
    armed: true,
    bio: "Vétéran de la gendarmerie nationale. Expertise en surveillance de sites industriels et escorte de valeurs.",
    competences: ['Surveillance industrielle', 'Escorte valeurs', 'Systèmes alarme', 'Investigation', 'Self-défense'],
    rating: 4.7,
    missions_count: 211,
    available: true,
    commune: 'Matam',
    photo_url: null,
    mission_types: ['surveillance_site', 'escorte_securisee', 'mission_sur_mesure'],
    status: 'active',
  },
  {
    id: 'agent-4',
    user_id: 'user-a4',
    phone: '+224620004004',
    name: 'Mariama Baldé',
    badge: 'SGP-2023-0112',
    experience: 3,
    armed: false,
    bio: 'Agent certifiée ONPSEC. Spécialisée sécurité résidentielle et accompagnement famille.',
    competences: ['Sécurité résidentielle', 'Accompagnement enfants', 'Premiers secours', 'Surveillance caméras'],
    rating: 4.6,
    missions_count: 45,
    available: true,
    commune: 'Ratoma',
    photo_url: null,
    mission_types: ['securite_residentielle', 'protection_evenement'],
    status: 'active',
  },
  {
    id: 'agent-5',
    user_id: 'user-a5',
    phone: '+224620005005',
    name: 'Sékou Sylla',
    badge: 'SGP-2019-0015',
    experience: 12,
    armed: true,
    bio: "Chef d'équipe sécurité. Expert en sécurité événements de grande envergure et protection institutionnelle.",
    competences: ['Management équipe', 'Sécurité VIP', 'Gestion foule', 'Planification', 'Formation'],
    rating: 5.0,
    missions_count: 312,
    available: false,
    commune: 'Kaloum',
    photo_url: null,
    mission_types: ['garde_corps_vip', 'protection_evenement', 'mission_sur_mesure'],
    status: 'active',
  },
  {
    id: 'agent-6',
    user_id: 'user-a6',
    phone: '+224620006006',
    name: 'Aissatou Diallo',
    badge: 'SGP-2022-0097',
    experience: 4,
    armed: false,
    bio: 'Ancienne policière reconvertie dans la sécurité privée. Spécialiste protection femmes et enfants.',
    competences: ['Protection femmes', 'Sécurité résidentielle', 'Médiation', 'Secourisme', 'Langues: Français, Pular, Soussou'],
    rating: 4.8,
    missions_count: 63,
    available: true,
    commune: 'Matoto',
    photo_url: null,
    mission_types: ['securite_residentielle', 'protection_evenement', 'garde_corps_vip'],
    status: 'active',
  },
]

export const MOCK_CLIENT = {
  id: 'client-demo-1',
  user_id: 'user-c1',
  phone: '+224622000001',
  name: 'Alpha Condé',
  email: 'alpha@example.com',
  role: 'client',
  commune: 'Kaloum',
  type_compte: 'particulier',
}

export const MOCK_AGENT_USER = MOCK_AGENTS[0]

export const MOCK_MISSIONS = [
  {
    id: 'mission-demo-1',
    client_id: 'client-demo-1',
    agent_id: 'agent-1',
    agent: MOCK_AGENTS[0],
    type: 'garde_corps_vip',
    title: 'Protection réunion business',
    description: 'Protection rapprochée pour réunion avec partenaires internationaux',
    duree_heures: 4,
    date_mission: new Date(Date.now() + 86400000).toISOString(),
    adresse: 'Hôtel Kaloum Palace, Conakry',
    urgence: 'normal',
    statut: 'accepted',
    prix_total: 630000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-demo-2',
    client_id: 'client-demo-1',
    agent_id: 'agent-2',
    agent: MOCK_AGENTS[1],
    type: 'protection_evenement',
    title: 'Sécurité mariage Dixinn',
    description: 'Sécurité pour cérémonie de mariage 200 invités',
    duree_heures: 6,
    date_mission: new Date(Date.now() + 172800000).toISOString(),
    adresse: 'Salle des fêtes Dixinn, Conakry',
    urgence: 'normal',
    statut: 'pending',
    prix_total: 630000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-demo-3',
    client_id: 'client-demo-1',
    agent_id: 'agent-3',
    agent: MOCK_AGENTS[2],
    type: 'surveillance_site',
    title: 'Surveillance chantier Matam',
    description: 'Surveillance nocturne chantier de construction',
    duree_heures: 8,
    date_mission: new Date(Date.now() - 86400000).toISOString(),
    adresse: 'Chantier Cité Matam, Conakry',
    urgence: 'normal',
    statut: 'completed',
    prix_total: 420000,
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

export const MOCK_MESSAGES = [
  { id: 1, from: 'agent', content: 'Bonjour, je suis disponible pour votre mission. Je serai à l\'heure.', time: '09:15' },
  { id: 2, from: 'client', content: 'Parfait. L\'entrée principale est au nord du bâtiment.', time: '09:20' },
  { id: 3, from: 'agent', content: 'Compris. J\'ai consulté le plan. À tout à l\'heure.', time: '09:25' },
]
